name: Update packages

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Update BB Launcher
        run: ./pkgs/bb-launcher/update.sh

      - name: Update shadPS4
        run: nix run nixpkgs#nix-update -- --flake --version-regex 'v\.(.*)' shadps4

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet && echo "No updates" && exit 0
          git add -A
          git commit -m "packages: update"
          git push
